name: proyecto_bloques
description: Aplicacion Flutter para el juego Proyecto Bloques.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
